# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

transitionsTime <- function(listaEventi, tempiTransizione, max_valore_evento) {
    .Call('pMineR_transitionsTime', PACKAGE = 'pMineR', listaEventi, tempiTransizione, max_valore_evento)
}

getInterestingSinglePatientData <- function(inputDF) {
    .Call('pMineR_getInterestingSinglePatientData', PACKAGE = 'pMineR', inputDF)
}

filterPatProcess <- function(PatProcess, arrayEventiDaRimuovere, arrayEventiDaTenere, eventColumnNumber) {
    .Call('pMineR_filterPatProcess', PACKAGE = 'pMineR', PatProcess, arrayEventiDaRimuovere, arrayEventiDaTenere, eventColumnNumber)
}

